// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: im.proto

#include "im.pb.h"
#include "im.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace im {

static const char* ChatTunnel_method_names[] = {
  "/im.ChatTunnel/Connect",
};

std::unique_ptr< ChatTunnel::Stub> ChatTunnel::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatTunnel::Stub> stub(new ChatTunnel::Stub(channel, options));
  return stub;
}

ChatTunnel::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Connect_(ChatTunnel_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::im::ClientFrame, ::im::ServerFrame>* ChatTunnel::Stub::ConnectRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::im::ClientFrame, ::im::ServerFrame>::Create(channel_.get(), rpcmethod_Connect_, context);
}

void ChatTunnel::Stub::async::Connect(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::im::ClientFrame,::im::ServerFrame>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::im::ClientFrame,::im::ServerFrame>::Create(stub_->channel_.get(), stub_->rpcmethod_Connect_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::im::ClientFrame, ::im::ServerFrame>* ChatTunnel::Stub::AsyncConnectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::im::ClientFrame, ::im::ServerFrame>::Create(channel_.get(), cq, rpcmethod_Connect_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::im::ClientFrame, ::im::ServerFrame>* ChatTunnel::Stub::PrepareAsyncConnectRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::im::ClientFrame, ::im::ServerFrame>::Create(channel_.get(), cq, rpcmethod_Connect_, context, false, nullptr);
}

ChatTunnel::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatTunnel_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< ChatTunnel::Service, ::im::ClientFrame, ::im::ServerFrame>(
          [](ChatTunnel::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::im::ServerFrame,
             ::im::ClientFrame>* stream) {
               return service->Connect(ctx, stream);
             }, this)));
}

ChatTunnel::Service::~Service() {
}

::grpc::Status ChatTunnel::Service::Connect(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::im::ServerFrame, ::im::ClientFrame>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ChatControlApi_method_names[] = {
  "/im.ChatControlApi/Sync",
  "/im.ChatControlApi/GetVerifyCode",
  "/im.ChatControlApi/Register",
  "/im.ChatControlApi/AuthLogin",
  "/im.ChatControlApi/ResetPassword",
  "/im.ChatControlApi/GetUserProfile",
  "/im.ChatControlApi/UpdateUserProfile",
  "/im.ChatControlApi/SearchUser",
  "/im.ChatControlApi/GetContacts",
  "/im.ChatControlApi/GetContactRequests",
  "/im.ChatControlApi/SendContactRequest",
  "/im.ChatControlApi/HandleContactRequest",
};

std::unique_ptr< ChatControlApi::Stub> ChatControlApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatControlApi::Stub> stub(new ChatControlApi::Stub(channel, options));
  return stub;
}

ChatControlApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Sync_(ChatControlApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetVerifyCode_(ChatControlApi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Register_(ChatControlApi_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AuthLogin_(ChatControlApi_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResetPassword_(ChatControlApi_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUserProfile_(ChatControlApi_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUserProfile_(ChatControlApi_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchUser_(ChatControlApi_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContacts_(ChatControlApi_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContactRequests_(ChatControlApi_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendContactRequest_(ChatControlApi_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleContactRequest_(ChatControlApi_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatControlApi::Stub::Sync(::grpc::ClientContext* context, const ::im::SyncReq& request, ::im::SyncResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::SyncReq, ::im::SyncResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sync_, context, request, response);
}

void ChatControlApi::Stub::async::Sync(::grpc::ClientContext* context, const ::im::SyncReq* request, ::im::SyncResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::SyncReq, ::im::SyncResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::Sync(::grpc::ClientContext* context, const ::im::SyncReq* request, ::im::SyncResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::SyncResp>* ChatControlApi::Stub::PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::im::SyncReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::SyncResp, ::im::SyncReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sync_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::SyncResp>* ChatControlApi::Stub::AsyncSyncRaw(::grpc::ClientContext* context, const ::im::SyncReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSyncRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::GetVerifyCode(::grpc::ClientContext* context, const ::im::GetVerifyCodeReq& request, ::im::GetVerifyCodeResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::GetVerifyCodeReq, ::im::GetVerifyCodeResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVerifyCode_, context, request, response);
}

void ChatControlApi::Stub::async::GetVerifyCode(::grpc::ClientContext* context, const ::im::GetVerifyCodeReq* request, ::im::GetVerifyCodeResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::GetVerifyCodeReq, ::im::GetVerifyCodeResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVerifyCode_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::GetVerifyCode(::grpc::ClientContext* context, const ::im::GetVerifyCodeReq* request, ::im::GetVerifyCodeResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVerifyCode_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::GetVerifyCodeResp>* ChatControlApi::Stub::PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::im::GetVerifyCodeReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::GetVerifyCodeResp, ::im::GetVerifyCodeReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVerifyCode_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::GetVerifyCodeResp>* ChatControlApi::Stub::AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::im::GetVerifyCodeReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVerifyCodeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::Register(::grpc::ClientContext* context, const ::im::RegisterReq& request, ::im::RegisterResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::RegisterReq, ::im::RegisterResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void ChatControlApi::Stub::async::Register(::grpc::ClientContext* context, const ::im::RegisterReq* request, ::im::RegisterResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::RegisterReq, ::im::RegisterResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::Register(::grpc::ClientContext* context, const ::im::RegisterReq* request, ::im::RegisterResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::RegisterResp>* ChatControlApi::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::im::RegisterReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::RegisterResp, ::im::RegisterReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::RegisterResp>* ChatControlApi::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::im::RegisterReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::AuthLogin(::grpc::ClientContext* context, const ::im::AuthLoginReq& request, ::im::AuthLoginResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::AuthLoginReq, ::im::AuthLoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AuthLogin_, context, request, response);
}

void ChatControlApi::Stub::async::AuthLogin(::grpc::ClientContext* context, const ::im::AuthLoginReq* request, ::im::AuthLoginResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::AuthLoginReq, ::im::AuthLoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthLogin_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::AuthLogin(::grpc::ClientContext* context, const ::im::AuthLoginReq* request, ::im::AuthLoginResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AuthLogin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::AuthLoginResp>* ChatControlApi::Stub::PrepareAsyncAuthLoginRaw(::grpc::ClientContext* context, const ::im::AuthLoginReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::AuthLoginResp, ::im::AuthLoginReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AuthLogin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::AuthLoginResp>* ChatControlApi::Stub::AsyncAuthLoginRaw(::grpc::ClientContext* context, const ::im::AuthLoginReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAuthLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::ResetPassword(::grpc::ClientContext* context, const ::im::ResetPasswordReq& request, ::im::ResetPasswordResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::ResetPasswordReq, ::im::ResetPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResetPassword_, context, request, response);
}

void ChatControlApi::Stub::async::ResetPassword(::grpc::ClientContext* context, const ::im::ResetPasswordReq* request, ::im::ResetPasswordResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::ResetPasswordReq, ::im::ResetPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResetPassword_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::ResetPassword(::grpc::ClientContext* context, const ::im::ResetPasswordReq* request, ::im::ResetPasswordResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResetPassword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::ResetPasswordResp>* ChatControlApi::Stub::PrepareAsyncResetPasswordRaw(::grpc::ClientContext* context, const ::im::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::ResetPasswordResp, ::im::ResetPasswordReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResetPassword_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::ResetPasswordResp>* ChatControlApi::Stub::AsyncResetPasswordRaw(::grpc::ClientContext* context, const ::im::ResetPasswordReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResetPasswordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::GetUserProfile(::grpc::ClientContext* context, const ::im::GetUserProfileReq& request, ::im::GetUserProfileResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::GetUserProfileReq, ::im::GetUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUserProfile_, context, request, response);
}

void ChatControlApi::Stub::async::GetUserProfile(::grpc::ClientContext* context, const ::im::GetUserProfileReq* request, ::im::GetUserProfileResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::GetUserProfileReq, ::im::GetUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::GetUserProfile(::grpc::ClientContext* context, const ::im::GetUserProfileReq* request, ::im::GetUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::GetUserProfileResp>* ChatControlApi::Stub::PrepareAsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::im::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::GetUserProfileResp, ::im::GetUserProfileReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUserProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::GetUserProfileResp>* ChatControlApi::Stub::AsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::im::GetUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::UpdateUserProfile(::grpc::ClientContext* context, const ::im::UpdateUserProfileReq& request, ::im::UpdateUserProfileResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::UpdateUserProfileReq, ::im::UpdateUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateUserProfile_, context, request, response);
}

void ChatControlApi::Stub::async::UpdateUserProfile(::grpc::ClientContext* context, const ::im::UpdateUserProfileReq* request, ::im::UpdateUserProfileResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::UpdateUserProfileReq, ::im::UpdateUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserProfile_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::UpdateUserProfile(::grpc::ClientContext* context, const ::im::UpdateUserProfileReq* request, ::im::UpdateUserProfileResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::UpdateUserProfileResp>* ChatControlApi::Stub::PrepareAsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::im::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::UpdateUserProfileResp, ::im::UpdateUserProfileReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateUserProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::UpdateUserProfileResp>* ChatControlApi::Stub::AsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::im::UpdateUserProfileReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateUserProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::SearchUser(::grpc::ClientContext* context, const ::im::SearchUserReq& request, ::im::SearchUserResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::SearchUserReq, ::im::SearchUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SearchUser_, context, request, response);
}

void ChatControlApi::Stub::async::SearchUser(::grpc::ClientContext* context, const ::im::SearchUserReq* request, ::im::SearchUserResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::SearchUserReq, ::im::SearchUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchUser_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::SearchUser(::grpc::ClientContext* context, const ::im::SearchUserReq* request, ::im::SearchUserResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::SearchUserResp>* ChatControlApi::Stub::PrepareAsyncSearchUserRaw(::grpc::ClientContext* context, const ::im::SearchUserReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::SearchUserResp, ::im::SearchUserReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SearchUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::SearchUserResp>* ChatControlApi::Stub::AsyncSearchUserRaw(::grpc::ClientContext* context, const ::im::SearchUserReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::GetContacts(::grpc::ClientContext* context, const ::im::GetContactsReq& request, ::im::GetContactsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::GetContactsReq, ::im::GetContactsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetContacts_, context, request, response);
}

void ChatControlApi::Stub::async::GetContacts(::grpc::ClientContext* context, const ::im::GetContactsReq* request, ::im::GetContactsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::GetContactsReq, ::im::GetContactsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContacts_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::GetContacts(::grpc::ClientContext* context, const ::im::GetContactsReq* request, ::im::GetContactsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContacts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::GetContactsResp>* ChatControlApi::Stub::PrepareAsyncGetContactsRaw(::grpc::ClientContext* context, const ::im::GetContactsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::GetContactsResp, ::im::GetContactsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetContacts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::GetContactsResp>* ChatControlApi::Stub::AsyncGetContactsRaw(::grpc::ClientContext* context, const ::im::GetContactsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetContactsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::GetContactRequests(::grpc::ClientContext* context, const ::im::GetContactRequestsReq& request, ::im::GetContactRequestsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::GetContactRequestsReq, ::im::GetContactRequestsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetContactRequests_, context, request, response);
}

void ChatControlApi::Stub::async::GetContactRequests(::grpc::ClientContext* context, const ::im::GetContactRequestsReq* request, ::im::GetContactRequestsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::GetContactRequestsReq, ::im::GetContactRequestsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContactRequests_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::GetContactRequests(::grpc::ClientContext* context, const ::im::GetContactRequestsReq* request, ::im::GetContactRequestsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContactRequests_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::GetContactRequestsResp>* ChatControlApi::Stub::PrepareAsyncGetContactRequestsRaw(::grpc::ClientContext* context, const ::im::GetContactRequestsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::GetContactRequestsResp, ::im::GetContactRequestsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetContactRequests_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::GetContactRequestsResp>* ChatControlApi::Stub::AsyncGetContactRequestsRaw(::grpc::ClientContext* context, const ::im::GetContactRequestsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetContactRequestsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::SendContactRequest(::grpc::ClientContext* context, const ::im::SendContactReqReq& request, ::im::SendContactReqResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::SendContactReqReq, ::im::SendContactReqResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendContactRequest_, context, request, response);
}

void ChatControlApi::Stub::async::SendContactRequest(::grpc::ClientContext* context, const ::im::SendContactReqReq* request, ::im::SendContactReqResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::SendContactReqReq, ::im::SendContactReqResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendContactRequest_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::SendContactRequest(::grpc::ClientContext* context, const ::im::SendContactReqReq* request, ::im::SendContactReqResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendContactRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::SendContactReqResp>* ChatControlApi::Stub::PrepareAsyncSendContactRequestRaw(::grpc::ClientContext* context, const ::im::SendContactReqReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::SendContactReqResp, ::im::SendContactReqReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendContactRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::SendContactReqResp>* ChatControlApi::Stub::AsyncSendContactRequestRaw(::grpc::ClientContext* context, const ::im::SendContactReqReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendContactRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatControlApi::Stub::HandleContactRequest(::grpc::ClientContext* context, const ::im::HandleContactReqReq& request, ::im::HandleContactReqResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::HandleContactReqReq, ::im::HandleContactReqResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleContactRequest_, context, request, response);
}

void ChatControlApi::Stub::async::HandleContactRequest(::grpc::ClientContext* context, const ::im::HandleContactReqReq* request, ::im::HandleContactReqResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::HandleContactReqReq, ::im::HandleContactReqResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleContactRequest_, context, request, response, std::move(f));
}

void ChatControlApi::Stub::async::HandleContactRequest(::grpc::ClientContext* context, const ::im::HandleContactReqReq* request, ::im::HandleContactReqResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleContactRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::HandleContactReqResp>* ChatControlApi::Stub::PrepareAsyncHandleContactRequestRaw(::grpc::ClientContext* context, const ::im::HandleContactReqReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::HandleContactReqResp, ::im::HandleContactReqReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleContactRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::HandleContactReqResp>* ChatControlApi::Stub::AsyncHandleContactRequestRaw(::grpc::ClientContext* context, const ::im::HandleContactReqReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleContactRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatControlApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::SyncReq, ::im::SyncResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::SyncReq* req,
             ::im::SyncResp* resp) {
               return service->Sync(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::GetVerifyCodeReq, ::im::GetVerifyCodeResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::GetVerifyCodeReq* req,
             ::im::GetVerifyCodeResp* resp) {
               return service->GetVerifyCode(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::RegisterReq, ::im::RegisterResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::RegisterReq* req,
             ::im::RegisterResp* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::AuthLoginReq, ::im::AuthLoginResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::AuthLoginReq* req,
             ::im::AuthLoginResp* resp) {
               return service->AuthLogin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::ResetPasswordReq, ::im::ResetPasswordResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::ResetPasswordReq* req,
             ::im::ResetPasswordResp* resp) {
               return service->ResetPassword(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::GetUserProfileReq, ::im::GetUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::GetUserProfileReq* req,
             ::im::GetUserProfileResp* resp) {
               return service->GetUserProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::UpdateUserProfileReq, ::im::UpdateUserProfileResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::UpdateUserProfileReq* req,
             ::im::UpdateUserProfileResp* resp) {
               return service->UpdateUserProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::SearchUserReq, ::im::SearchUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::SearchUserReq* req,
             ::im::SearchUserResp* resp) {
               return service->SearchUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::GetContactsReq, ::im::GetContactsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::GetContactsReq* req,
             ::im::GetContactsResp* resp) {
               return service->GetContacts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::GetContactRequestsReq, ::im::GetContactRequestsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::GetContactRequestsReq* req,
             ::im::GetContactRequestsResp* resp) {
               return service->GetContactRequests(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::SendContactReqReq, ::im::SendContactReqResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::SendContactReqReq* req,
             ::im::SendContactReqResp* resp) {
               return service->SendContactRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatControlApi_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatControlApi::Service, ::im::HandleContactReqReq, ::im::HandleContactReqResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatControlApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::HandleContactReqReq* req,
             ::im::HandleContactReqResp* resp) {
               return service->HandleContactRequest(ctx, req, resp);
             }, this)));
}

ChatControlApi::Service::~Service() {
}

::grpc::Status ChatControlApi::Service::Sync(::grpc::ServerContext* context, const ::im::SyncReq* request, ::im::SyncResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::GetVerifyCode(::grpc::ServerContext* context, const ::im::GetVerifyCodeReq* request, ::im::GetVerifyCodeResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::Register(::grpc::ServerContext* context, const ::im::RegisterReq* request, ::im::RegisterResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::AuthLogin(::grpc::ServerContext* context, const ::im::AuthLoginReq* request, ::im::AuthLoginResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::ResetPassword(::grpc::ServerContext* context, const ::im::ResetPasswordReq* request, ::im::ResetPasswordResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::GetUserProfile(::grpc::ServerContext* context, const ::im::GetUserProfileReq* request, ::im::GetUserProfileResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::UpdateUserProfile(::grpc::ServerContext* context, const ::im::UpdateUserProfileReq* request, ::im::UpdateUserProfileResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::SearchUser(::grpc::ServerContext* context, const ::im::SearchUserReq* request, ::im::SearchUserResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::GetContacts(::grpc::ServerContext* context, const ::im::GetContactsReq* request, ::im::GetContactsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::GetContactRequests(::grpc::ServerContext* context, const ::im::GetContactRequestsReq* request, ::im::GetContactRequestsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::SendContactRequest(::grpc::ServerContext* context, const ::im::SendContactReqReq* request, ::im::SendContactReqResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatControlApi::Service::HandleContactRequest(::grpc::ServerContext* context, const ::im::HandleContactReqReq* request, ::im::HandleContactReqResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* ChatApi_method_names[] = {
  "/im.ChatApi/SendMessage",
  "/im.ChatApi/Ack",
  "/im.ChatApi/Sync",
};

std::unique_ptr< ChatApi::Stub> ChatApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatApi::Stub> stub(new ChatApi::Stub(channel, options));
  return stub;
}

ChatApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendMessage_(ChatApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ack_(ChatApi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Sync_(ChatApi_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatApi::Stub::SendMessage(::grpc::ClientContext* context, const ::im::SendMessageReq& request, ::im::SendMessageResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::SendMessageReq, ::im::SendMessageResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMessage_, context, request, response);
}

void ChatApi::Stub::async::SendMessage(::grpc::ClientContext* context, const ::im::SendMessageReq* request, ::im::SendMessageResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::SendMessageReq, ::im::SendMessageResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, std::move(f));
}

void ChatApi::Stub::async::SendMessage(::grpc::ClientContext* context, const ::im::SendMessageReq* request, ::im::SendMessageResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::SendMessageResp>* ChatApi::Stub::PrepareAsyncSendMessageRaw(::grpc::ClientContext* context, const ::im::SendMessageReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::SendMessageResp, ::im::SendMessageReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::SendMessageResp>* ChatApi::Stub::AsyncSendMessageRaw(::grpc::ClientContext* context, const ::im::SendMessageReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatApi::Stub::Ack(::grpc::ClientContext* context, const ::im::AckUpReq& request, ::im::AckUpResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::AckUpReq, ::im::AckUpResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ack_, context, request, response);
}

void ChatApi::Stub::async::Ack(::grpc::ClientContext* context, const ::im::AckUpReq* request, ::im::AckUpResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::AckUpReq, ::im::AckUpResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ack_, context, request, response, std::move(f));
}

void ChatApi::Stub::async::Ack(::grpc::ClientContext* context, const ::im::AckUpReq* request, ::im::AckUpResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ack_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::AckUpResp>* ChatApi::Stub::PrepareAsyncAckRaw(::grpc::ClientContext* context, const ::im::AckUpReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::AckUpResp, ::im::AckUpReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ack_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::AckUpResp>* ChatApi::Stub::AsyncAckRaw(::grpc::ClientContext* context, const ::im::AckUpReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatApi::Stub::Sync(::grpc::ClientContext* context, const ::im::SyncUpReq& request, ::im::SyncUpResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::SyncUpReq, ::im::SyncUpResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Sync_, context, request, response);
}

void ChatApi::Stub::async::Sync(::grpc::ClientContext* context, const ::im::SyncUpReq* request, ::im::SyncUpResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::SyncUpReq, ::im::SyncUpResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, std::move(f));
}

void ChatApi::Stub::async::Sync(::grpc::ClientContext* context, const ::im::SyncUpReq* request, ::im::SyncUpResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Sync_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::SyncUpResp>* ChatApi::Stub::PrepareAsyncSyncRaw(::grpc::ClientContext* context, const ::im::SyncUpReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::SyncUpResp, ::im::SyncUpReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Sync_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::SyncUpResp>* ChatApi::Stub::AsyncSyncRaw(::grpc::ClientContext* context, const ::im::SyncUpReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSyncRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatApi::Service, ::im::SendMessageReq, ::im::SendMessageResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::SendMessageReq* req,
             ::im::SendMessageResp* resp) {
               return service->SendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatApi::Service, ::im::AckUpReq, ::im::AckUpResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::AckUpReq* req,
             ::im::AckUpResp* resp) {
               return service->Ack(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatApi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatApi::Service, ::im::SyncUpReq, ::im::SyncUpResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::SyncUpReq* req,
             ::im::SyncUpResp* resp) {
               return service->Sync(ctx, req, resp);
             }, this)));
}

ChatApi::Service::~Service() {
}

::grpc::Status ChatApi::Service::SendMessage(::grpc::ServerContext* context, const ::im::SendMessageReq* request, ::im::SendMessageResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatApi::Service::Ack(::grpc::ServerContext* context, const ::im::AckUpReq* request, ::im::AckUpResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatApi::Service::Sync(::grpc::ServerContext* context, const ::im::SyncUpReq* request, ::im::SyncUpResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* DeliverApi_method_names[] = {
  "/im.DeliverApi/DeliverToUser",
  "/im.DeliverApi/DeliverBatch",
};

std::unique_ptr< DeliverApi::Stub> DeliverApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DeliverApi::Stub> stub(new DeliverApi::Stub(channel, options));
  return stub;
}

DeliverApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_DeliverToUser_(DeliverApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeliverBatch_(DeliverApi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DeliverApi::Stub::DeliverToUser(::grpc::ClientContext* context, const ::im::DeliverToUserReq& request, ::im::DeliverToUserResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::DeliverToUserReq, ::im::DeliverToUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeliverToUser_, context, request, response);
}

void DeliverApi::Stub::async::DeliverToUser(::grpc::ClientContext* context, const ::im::DeliverToUserReq* request, ::im::DeliverToUserResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::DeliverToUserReq, ::im::DeliverToUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeliverToUser_, context, request, response, std::move(f));
}

void DeliverApi::Stub::async::DeliverToUser(::grpc::ClientContext* context, const ::im::DeliverToUserReq* request, ::im::DeliverToUserResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeliverToUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::DeliverToUserResp>* DeliverApi::Stub::PrepareAsyncDeliverToUserRaw(::grpc::ClientContext* context, const ::im::DeliverToUserReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::DeliverToUserResp, ::im::DeliverToUserReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeliverToUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::DeliverToUserResp>* DeliverApi::Stub::AsyncDeliverToUserRaw(::grpc::ClientContext* context, const ::im::DeliverToUserReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeliverToUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status DeliverApi::Stub::DeliverBatch(::grpc::ClientContext* context, const ::im::DeliverBatchReq& request, ::im::DeliverBatchResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::im::DeliverBatchReq, ::im::DeliverBatchResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeliverBatch_, context, request, response);
}

void DeliverApi::Stub::async::DeliverBatch(::grpc::ClientContext* context, const ::im::DeliverBatchReq* request, ::im::DeliverBatchResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::im::DeliverBatchReq, ::im::DeliverBatchResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeliverBatch_, context, request, response, std::move(f));
}

void DeliverApi::Stub::async::DeliverBatch(::grpc::ClientContext* context, const ::im::DeliverBatchReq* request, ::im::DeliverBatchResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeliverBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::im::DeliverBatchResp>* DeliverApi::Stub::PrepareAsyncDeliverBatchRaw(::grpc::ClientContext* context, const ::im::DeliverBatchReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::im::DeliverBatchResp, ::im::DeliverBatchReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeliverBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::im::DeliverBatchResp>* DeliverApi::Stub::AsyncDeliverBatchRaw(::grpc::ClientContext* context, const ::im::DeliverBatchReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeliverBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

DeliverApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeliverApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeliverApi::Service, ::im::DeliverToUserReq, ::im::DeliverToUserResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeliverApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::DeliverToUserReq* req,
             ::im::DeliverToUserResp* resp) {
               return service->DeliverToUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DeliverApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DeliverApi::Service, ::im::DeliverBatchReq, ::im::DeliverBatchResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DeliverApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::im::DeliverBatchReq* req,
             ::im::DeliverBatchResp* resp) {
               return service->DeliverBatch(ctx, req, resp);
             }, this)));
}

DeliverApi::Service::~Service() {
}

::grpc::Status DeliverApi::Service::DeliverToUser(::grpc::ServerContext* context, const ::im::DeliverToUserReq* request, ::im::DeliverToUserResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status DeliverApi::Service::DeliverBatch(::grpc::ServerContext* context, const ::im::DeliverBatchReq* request, ::im::DeliverBatchResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace im

