// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: userserver.proto

#include "userserver.pb.h"
#include "userserver.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* UserService_method_names[] = {
  "/UserService/VerifyCredentials",
  "/UserService/CreateUser",
  "/UserService/GetUserProfile",
  "/UserService/UpdateUserProfile",
  "/UserService/ResetPassword",
  "/UserService/SearchUser",
  "/UserService/SendContactRequest",
  "/UserService/HandleContactRequest",
  "/UserService/GetContacts",
  "/UserService/GetContactRequests",
};

std::unique_ptr< UserService::Stub> UserService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserService::Stub> stub(new UserService::Stub(channel, options));
  return stub;
}

UserService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_VerifyCredentials_(UserService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CreateUser_(UserService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetUserProfile_(UserService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateUserProfile_(UserService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ResetPassword_(UserService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SearchUser_(UserService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SendContactRequest_(UserService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HandleContactRequest_(UserService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContacts_(UserService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetContactRequests_(UserService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserService::Stub::VerifyCredentials(::grpc::ClientContext* context, const ::VerifyCredentialsRequest& request, ::VerifyCredentialsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::VerifyCredentialsRequest, ::VerifyCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_VerifyCredentials_, context, request, response);
}

void UserService::Stub::async::VerifyCredentials(::grpc::ClientContext* context, const ::VerifyCredentialsRequest* request, ::VerifyCredentialsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::VerifyCredentialsRequest, ::VerifyCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyCredentials_, context, request, response, std::move(f));
}

void UserService::Stub::async::VerifyCredentials(::grpc::ClientContext* context, const ::VerifyCredentialsRequest* request, ::VerifyCredentialsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_VerifyCredentials_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::VerifyCredentialsResponse>* UserService::Stub::PrepareAsyncVerifyCredentialsRaw(::grpc::ClientContext* context, const ::VerifyCredentialsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::VerifyCredentialsResponse, ::VerifyCredentialsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_VerifyCredentials_, context, request);
}

::grpc::ClientAsyncResponseReader< ::VerifyCredentialsResponse>* UserService::Stub::AsyncVerifyCredentialsRaw(::grpc::ClientContext* context, const ::VerifyCredentialsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncVerifyCredentialsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::CreateUser(::grpc::ClientContext* context, const ::CreateUserRequest& request, ::CreateUserResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CreateUserRequest, ::CreateUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateUser_, context, request, response);
}

void UserService::Stub::async::CreateUser(::grpc::ClientContext* context, const ::CreateUserRequest* request, ::CreateUserResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CreateUserRequest, ::CreateUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateUser_, context, request, response, std::move(f));
}

void UserService::Stub::async::CreateUser(::grpc::ClientContext* context, const ::CreateUserRequest* request, ::CreateUserResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::CreateUserResponse>* UserService::Stub::PrepareAsyncCreateUserRaw(::grpc::ClientContext* context, const ::CreateUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::CreateUserResponse, ::CreateUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::CreateUserResponse>* UserService::Stub::AsyncCreateUserRaw(::grpc::ClientContext* context, const ::CreateUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::GetUserProfile(::grpc::ClientContext* context, const ::GetUserProfileRequest& request, ::GetUserProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetUserProfileRequest, ::GetUserProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetUserProfile_, context, request, response);
}

void UserService::Stub::async::GetUserProfile(::grpc::ClientContext* context, const ::GetUserProfileRequest* request, ::GetUserProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetUserProfileRequest, ::GetUserProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, std::move(f));
}

void UserService::Stub::async::GetUserProfile(::grpc::ClientContext* context, const ::GetUserProfileRequest* request, ::GetUserProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetUserProfileResponse>* UserService::Stub::PrepareAsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::GetUserProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetUserProfileResponse, ::GetUserProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetUserProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetUserProfileResponse>* UserService::Stub::AsyncGetUserProfileRaw(::grpc::ClientContext* context, const ::GetUserProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetUserProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::UpdateUserProfile(::grpc::ClientContext* context, const ::UpdateUserProfileRequest& request, ::UpdateUserProfileResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::UpdateUserProfileRequest, ::UpdateUserProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateUserProfile_, context, request, response);
}

void UserService::Stub::async::UpdateUserProfile(::grpc::ClientContext* context, const ::UpdateUserProfileRequest* request, ::UpdateUserProfileResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::UpdateUserProfileRequest, ::UpdateUserProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserProfile_, context, request, response, std::move(f));
}

void UserService::Stub::async::UpdateUserProfile(::grpc::ClientContext* context, const ::UpdateUserProfileRequest* request, ::UpdateUserProfileResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateUserProfile_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::UpdateUserProfileResponse>* UserService::Stub::PrepareAsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::UpdateUserProfileRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::UpdateUserProfileResponse, ::UpdateUserProfileRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateUserProfile_, context, request);
}

::grpc::ClientAsyncResponseReader< ::UpdateUserProfileResponse>* UserService::Stub::AsyncUpdateUserProfileRaw(::grpc::ClientContext* context, const ::UpdateUserProfileRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateUserProfileRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::ResetPassword(::grpc::ClientContext* context, const ::ResetPasswordRequest& request, ::ResetPasswordResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ResetPasswordRequest, ::ResetPasswordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ResetPassword_, context, request, response);
}

void UserService::Stub::async::ResetPassword(::grpc::ClientContext* context, const ::ResetPasswordRequest* request, ::ResetPasswordResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ResetPasswordRequest, ::ResetPasswordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResetPassword_, context, request, response, std::move(f));
}

void UserService::Stub::async::ResetPassword(::grpc::ClientContext* context, const ::ResetPasswordRequest* request, ::ResetPasswordResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ResetPassword_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ResetPasswordResponse>* UserService::Stub::PrepareAsyncResetPasswordRaw(::grpc::ClientContext* context, const ::ResetPasswordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ResetPasswordResponse, ::ResetPasswordRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ResetPassword_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ResetPasswordResponse>* UserService::Stub::AsyncResetPasswordRaw(::grpc::ClientContext* context, const ::ResetPasswordRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncResetPasswordRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::SearchUser(::grpc::ClientContext* context, const ::SearchUserRequest& request, ::SearchUserResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SearchUserRequest, ::SearchUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SearchUser_, context, request, response);
}

void UserService::Stub::async::SearchUser(::grpc::ClientContext* context, const ::SearchUserRequest* request, ::SearchUserResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SearchUserRequest, ::SearchUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchUser_, context, request, response, std::move(f));
}

void UserService::Stub::async::SearchUser(::grpc::ClientContext* context, const ::SearchUserRequest* request, ::SearchUserResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SearchUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SearchUserResponse>* UserService::Stub::PrepareAsyncSearchUserRaw(::grpc::ClientContext* context, const ::SearchUserRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SearchUserResponse, ::SearchUserRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SearchUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SearchUserResponse>* UserService::Stub::AsyncSearchUserRaw(::grpc::ClientContext* context, const ::SearchUserRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSearchUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::SendContactRequest(::grpc::ClientContext* context, const ::SendContactRequestReq& request, ::SendContactRequestResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SendContactRequestReq, ::SendContactRequestResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendContactRequest_, context, request, response);
}

void UserService::Stub::async::SendContactRequest(::grpc::ClientContext* context, const ::SendContactRequestReq* request, ::SendContactRequestResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SendContactRequestReq, ::SendContactRequestResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendContactRequest_, context, request, response, std::move(f));
}

void UserService::Stub::async::SendContactRequest(::grpc::ClientContext* context, const ::SendContactRequestReq* request, ::SendContactRequestResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendContactRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::SendContactRequestResp>* UserService::Stub::PrepareAsyncSendContactRequestRaw(::grpc::ClientContext* context, const ::SendContactRequestReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::SendContactRequestResp, ::SendContactRequestReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendContactRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::SendContactRequestResp>* UserService::Stub::AsyncSendContactRequestRaw(::grpc::ClientContext* context, const ::SendContactRequestReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendContactRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::HandleContactRequest(::grpc::ClientContext* context, const ::HandleContactRequestReq& request, ::HandleContactRequestResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::HandleContactRequestReq, ::HandleContactRequestResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HandleContactRequest_, context, request, response);
}

void UserService::Stub::async::HandleContactRequest(::grpc::ClientContext* context, const ::HandleContactRequestReq* request, ::HandleContactRequestResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::HandleContactRequestReq, ::HandleContactRequestResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleContactRequest_, context, request, response, std::move(f));
}

void UserService::Stub::async::HandleContactRequest(::grpc::ClientContext* context, const ::HandleContactRequestReq* request, ::HandleContactRequestResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HandleContactRequest_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::HandleContactRequestResp>* UserService::Stub::PrepareAsyncHandleContactRequestRaw(::grpc::ClientContext* context, const ::HandleContactRequestReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::HandleContactRequestResp, ::HandleContactRequestReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HandleContactRequest_, context, request);
}

::grpc::ClientAsyncResponseReader< ::HandleContactRequestResp>* UserService::Stub::AsyncHandleContactRequestRaw(::grpc::ClientContext* context, const ::HandleContactRequestReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHandleContactRequestRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::GetContacts(::grpc::ClientContext* context, const ::GetContactsReq& request, ::GetContactsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetContactsReq, ::GetContactsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetContacts_, context, request, response);
}

void UserService::Stub::async::GetContacts(::grpc::ClientContext* context, const ::GetContactsReq* request, ::GetContactsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetContactsReq, ::GetContactsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContacts_, context, request, response, std::move(f));
}

void UserService::Stub::async::GetContacts(::grpc::ClientContext* context, const ::GetContactsReq* request, ::GetContactsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContacts_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetContactsResp>* UserService::Stub::PrepareAsyncGetContactsRaw(::grpc::ClientContext* context, const ::GetContactsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetContactsResp, ::GetContactsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetContacts_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetContactsResp>* UserService::Stub::AsyncGetContactsRaw(::grpc::ClientContext* context, const ::GetContactsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetContactsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status UserService::Stub::GetContactRequests(::grpc::ClientContext* context, const ::GetContactRequestsReq& request, ::GetContactRequestsResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::GetContactRequestsReq, ::GetContactRequestsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetContactRequests_, context, request, response);
}

void UserService::Stub::async::GetContactRequests(::grpc::ClientContext* context, const ::GetContactRequestsReq* request, ::GetContactRequestsResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::GetContactRequestsReq, ::GetContactRequestsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContactRequests_, context, request, response, std::move(f));
}

void UserService::Stub::async::GetContactRequests(::grpc::ClientContext* context, const ::GetContactRequestsReq* request, ::GetContactRequestsResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetContactRequests_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::GetContactRequestsResp>* UserService::Stub::PrepareAsyncGetContactRequestsRaw(::grpc::ClientContext* context, const ::GetContactRequestsReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::GetContactRequestsResp, ::GetContactRequestsReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetContactRequests_, context, request);
}

::grpc::ClientAsyncResponseReader< ::GetContactRequestsResp>* UserService::Stub::AsyncGetContactRequestsRaw(::grpc::ClientContext* context, const ::GetContactRequestsReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetContactRequestsRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::VerifyCredentialsRequest, ::VerifyCredentialsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::VerifyCredentialsRequest* req,
             ::VerifyCredentialsResponse* resp) {
               return service->VerifyCredentials(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::CreateUserRequest, ::CreateUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CreateUserRequest* req,
             ::CreateUserResponse* resp) {
               return service->CreateUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::GetUserProfileRequest, ::GetUserProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetUserProfileRequest* req,
             ::GetUserProfileResponse* resp) {
               return service->GetUserProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::UpdateUserProfileRequest, ::UpdateUserProfileResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::UpdateUserProfileRequest* req,
             ::UpdateUserProfileResponse* resp) {
               return service->UpdateUserProfile(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::ResetPasswordRequest, ::ResetPasswordResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ResetPasswordRequest* req,
             ::ResetPasswordResponse* resp) {
               return service->ResetPassword(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::SearchUserRequest, ::SearchUserResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SearchUserRequest* req,
             ::SearchUserResponse* resp) {
               return service->SearchUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::SendContactRequestReq, ::SendContactRequestResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SendContactRequestReq* req,
             ::SendContactRequestResp* resp) {
               return service->SendContactRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::HandleContactRequestReq, ::HandleContactRequestResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::HandleContactRequestReq* req,
             ::HandleContactRequestResp* resp) {
               return service->HandleContactRequest(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::GetContactsReq, ::GetContactsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetContactsReq* req,
             ::GetContactsResp* resp) {
               return service->GetContacts(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserService::Service, ::GetContactRequestsReq, ::GetContactRequestsResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::GetContactRequestsReq* req,
             ::GetContactRequestsResp* resp) {
               return service->GetContactRequests(ctx, req, resp);
             }, this)));
}

UserService::Service::~Service() {
}

::grpc::Status UserService::Service::VerifyCredentials(::grpc::ServerContext* context, const ::VerifyCredentialsRequest* request, ::VerifyCredentialsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::CreateUser(::grpc::ServerContext* context, const ::CreateUserRequest* request, ::CreateUserResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetUserProfile(::grpc::ServerContext* context, const ::GetUserProfileRequest* request, ::GetUserProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::UpdateUserProfile(::grpc::ServerContext* context, const ::UpdateUserProfileRequest* request, ::UpdateUserProfileResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::ResetPassword(::grpc::ServerContext* context, const ::ResetPasswordRequest* request, ::ResetPasswordResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::SearchUser(::grpc::ServerContext* context, const ::SearchUserRequest* request, ::SearchUserResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::SendContactRequest(::grpc::ServerContext* context, const ::SendContactRequestReq* request, ::SendContactRequestResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::HandleContactRequest(::grpc::ServerContext* context, const ::HandleContactRequestReq* request, ::HandleContactRequestResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetContacts(::grpc::ServerContext* context, const ::GetContactsReq* request, ::GetContactsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status UserService::Service::GetContactRequests(::grpc::ServerContext* context, const ::GetContactRequestsReq* request, ::GetContactRequestsResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


